apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: weimin
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        metrics: "true"
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: limanx
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          #volumeMounts:
          #- name: mysql-persistent-storage
          #  mountPath: /var/lib/mysql
      #volumes:
      #  - name: mysql-persistent-storage
      #    persistentVolumeClaim:
      #      claimName: mysql-pv-claim

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: weimin
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: web
  selector:
    app: mysql